//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AllContactInfoScrapper.LocalizationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AllContactInfoScrapper.LocalizationResources.MainRes", typeof(MainRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha Error. Follow this steps:
        ///Solve the captcha in the browser..
        /// </summary>
        public static string CaptchaInfo {
            get {
                return ResourceManager.GetString("CaptchaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha Error.
        /// </summary>
        public static string CaptchaTitle {
            get {
                return ResourceManager.GetString("CaptchaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Scraping completed!.
        /// </summary>
        public static string completedMsg {
            get {
                return ResourceManager.GetString("completedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string completedTitle {
            get {
                return ResourceManager.GetString("completedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains all kewyords and email.
        /// </summary>
        public static string ContainsAll {
            get {
                return ResourceManager.GetString("ContainsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains any kewyords and/or emails.
        /// </summary>
        public static string ContainsAny {
            get {
                return ResourceManager.GetString("ContainsAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csv.
        /// </summary>
        public static string csvExt {
            get {
                return ResourceManager.GetString("csvExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV file (*.csv).
        /// </summary>
        public static string csvFileName {
            get {
                return ResourceManager.GetString("csvFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading the necessary version of Chrome. It may take a few minutes..
        /// </summary>
        public static string DownloadingWarning {
            get {
                return ResourceManager.GetString("DownloadingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced mode.
        /// </summary>
        public static string EnhancedText {
            get {
                return ResourceManager.GetString("EnhancedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows results from all web pages containing the selected domain.
        /// </summary>
        public static string EnhancedTip {
            get {
                return ResourceManager.GetString("EnhancedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error in the application.
        ///Review the Log file that has been generated in the application folder..
        /// </summary>
        public static string ErrorInfo {
            get {
                return ResourceManager.GetString("ErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xls.
        /// </summary>
        public static string ExcelExt {
            get {
                return ResourceManager.GetString("ExcelExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel file (*.xls).
        /// </summary>
        public static string ExcelFileName {
            get {
                return ResourceManager.GetString("ExcelFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CSV.
        /// </summary>
        public static string ExportCsv {
            get {
                return ResourceManager.GetString("ExportCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data exported successfully!.
        /// </summary>
        public static string exportedOk {
            get {
                return ResourceManager.GetString("exportedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export EXCEL.
        /// </summary>
        public static string ExportExcel {
            get {
                return ResourceManager.GetString("ExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string exportTitle {
            get {
                return ResourceManager.GetString("exportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string HeadDesc {
            get {
                return ResourceManager.GetString("HeadDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string HeadEmail {
            get {
                return ResourceManager.GetString("HeadEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string HeadPhone {
            get {
                return ResourceManager.GetString("HeadPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string HeadTitle {
            get {
                return ResourceManager.GetString("HeadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string HeadUrl {
            get {
                return ResourceManager.GetString("HeadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails (comma separated).
        /// </summary>
        public static string LabelEmails {
            get {
                return ResourceManager.GetString("LabelEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords (comma separated).
        /// </summary>
        public static string LabelKeys {
            get {
                return ResourceManager.GetString("LabelKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch.
        /// </summary>
        public static string Launch {
            get {
                return ResourceManager.GetString("Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About  All Contact Info Scrapper.
        /// </summary>
        public static string mnAbout {
            get {
                return ResourceManager.GetString("mnAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string mnActivate {
            get {
                return ResourceManager.GetString("mnActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string mnExit {
            get {
                return ResourceManager.GetString("mnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string mnSettings {
            get {
                return ResourceManager.GetString("mnSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted mode.
        /// </summary>
        public static string RestrictedText {
            get {
                return ResourceManager.GetString("RestrictedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only show results from the selected domain.
        /// </summary>
        public static string RestrictedTip {
            get {
                return ResourceManager.GetString("RestrictedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Contacts:.
        /// </summary>
        public static string TotalContacts {
            get {
                return ResourceManager.GetString("TotalContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Emails:.
        /// </summary>
        public static string TotalEmails {
            get {
                return ResourceManager.GetString("TotalEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Phones:.
        /// </summary>
        public static string TotalPhones {
            get {
                return ResourceManager.GetString("TotalPhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Contact Info Scrapper.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
